import { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

// Define translations for different languages
const translations = {
  en: {
    home: 'Home',
    liveTracking: 'Live Tracking',
    routes: 'Routes',
    sustainability: 'Sustainability',
    profile: 'Profile',
    feedback: 'Feedback',
    profileSettings: 'Settings',
    login: 'Login',
    loading: 'Loading',
    pleaseWait: 'Please wait...',
    footer: '© {year} TransitTrack',
    // Accessibility page translations
    accessibilityAndSettings: 'Accessibility & Settings',
    customizeExperience: 'Customize your experience for better accessibility and language preferences',
    resetToDefault: 'Reset to Default',
    visualAccessibility: 'Visual Accessibility',
    fontSize: 'Font Size',
    small: 'Small (14px)',
    medium: 'Medium (16px)',
    large: 'Large (18px)',
    extraLarge: 'Extra Large (22px)',
    highContrastMode: 'High Contrast Mode',
    increaseContrast: 'Increase contrast for better visibility',
    reduceMotion: 'Reduce Motion',
    reduceMotionDesc: 'Minimize animations and transitions',
    colorBlindSupport: 'Color Blind Support',
    colorBlindSupportDesc: 'Optimize colors for different types of color blindness',
    audioAccessibility: 'Audio Accessibility',
    voiceAnnouncements: 'Voice Announcements',
    voiceAnnouncementsDesc: 'Announce bus arrivals and important updates',
    testVoice: 'Test Voice',
    screenReader: 'Screen Reader Optimization',
    screenReaderDesc: 'Improve compatibility with screen readers',
    languagePreferences: 'Language Preferences',
    selectLanguage: 'Select Language',
    // Feedback page translations
    submitFeedback: 'Submit Feedback',
    viewFeedback: 'View Feedback',
    feedbackType: 'Feedback Type',
    reportIssue: 'Report an Issue',
    suggestRoute: 'Suggest a Route',
    rateBus: 'Rate a Bus',
    giveCompliment: 'Give Compliment',
    busRoute: 'Bus Route',
    feedbackTitle: 'Title',
    feedbackDescription: 'Description',
    priority: 'Priority',
    low: 'Low',
    mediumPriority: 'Medium',
    high: 'High',
    anonymous: 'Submit Anonymously',
    contactInfo: 'Contact Information (optional)',
    submitButton: 'Submit Feedback',
    filterBy: 'Filter by',
    all: 'All',
    issues: 'Issues',
    suggestions: 'Suggestions',
    ratings: 'Ratings',
    compliments: 'Compliments',
    // Profile page translations
    myRides: 'My Rides',
    favorites: 'Favorites',
    settings: 'Settings',
    notifications: 'Notifications',
    darkMode: 'Dark Mode',
    dataSaver: 'Data Saver',
    locationTracking: 'Location Tracking',
    pushAlerts: 'Push Alerts',
    emailUpdates: 'Email Updates',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    totalTrips: 'Total Trips',
    totalDistance: 'Total Distance',
    co2SavedProfile: 'CO₂ Saved',
    profileMoneySaved: 'Money Saved',
    tripFrom: 'From',
    tripTo: 'To',
    tripDate: 'Date',
    tripTime: 'Time',
    tripFare: 'Fare',
    // Home page translations
    smarterCommutes: 'Smarter Commutes,',
    greenerCities: 'Greener Cities',
    experienceFuture: 'Experience the future of public transportation with AI-powered tracking, real-time crowd predictions, and environmental impact monitoring.',
    trackBusesNow: 'Track Buses Now',
    viewRoutes: 'View Routes',
    whyChooseTransitTrack: 'Why Choose TransitTrack?',
    platformCombines: 'Our platform combines cutting-edge technology with user-friendly design to transform your commuting experience.',
    "Real-TimeTracking": 'Real-Time Tracking',
    "Real-TimeTrackingDesc": 'Track buses live with precise location data and accurate arrival predictions',
    "AICrowdPrediction": 'AI Crowd Prediction',
    "AICrowdPredictionDesc": 'Smart algorithms predict crowd density to help you plan comfortable journeys',
    "CarbonSavingsTracker": 'Carbon Savings Tracker',
    "CarbonSavingsTrackerDesc": 'Monitor your environmental impact and see how much CO₂ you save with every trip',
    findYourBus: 'Find Your Bus',
    enterYourRoute: 'Enter your route or destination to get instant tracking',
    routeNumberPlaceholder: 'Route number, bus stop, or destination...',
    searchNow: 'Search Now',
    searching: 'Searching...',
    popularSearches: 'Popular searches:',
    liveTransitMap: 'Live Transit Map',
    realTimeVisualization: 'Real-time visualization of active buses in your area',
    activeNow: 'Active now:',
    busesNearby: '{count} buses nearby',
    openFullMap: 'Open Full Map',
    advancedFeatures: 'Advanced features designed for modern commuters and sustainable transportation',
    readyToTransform: 'Ready to Transform Your Commute?',
    joinThousands: 'Join thousands of smart commuters making a positive impact on the environment',
    startTrackingNow: 'Start Tracking Now',
    seeEnvironmentalImpact: 'See Environmental Impact',
    dailyCommuters: 'Daily Commuters',
    activeRoutes: 'Active Routes',
    accuracyRate: 'Accuracy Rate',
    co2TonsSaved: 'CO₂ Tons Saved',
    // LiveTracking.jsx translations
    offlineMode: 'Offline mode - showing cached data',
    liveBusTracking: 'Live Bus Tracking',
    live: 'Live',
    offline: 'Offline',
    trackBusesDescription: 'Track buses in real-time with AI-powered crowd predictions',
    searchRoutesStops: 'Search routes, stops...',
    
    // GreenScore.jsx translations
    co2Saved: 'CO₂ Saved',
    tripsTaken: 'Trips Taken',
    kmTraveled: 'km traveled',
    moneySaved: 'Money Saved',
    treesEquivalent: 'trees planted',
    comparedToPrivateTransport: 'Compared to using private transport',
    equivalentTo: 'Equivalent to',
    allCrowds: 'All Crowds',
    seatsAvailable: 'Seats Available',
    moderate: 'Moderate',
    crowded: 'Crowded',
    // Login page translations
    welcomeBack: 'Welcome Back',
    loginToDashboard: 'Login to access your dashboard',
    emailAddress: 'Email Address',
    password: 'Password',
    // RoutesTimetable.jsx translations
    planYourRoute: 'Plan Your Route',
    routeFrom: 'From',
    routeTo: 'To',
    findRoutes: 'Find Routes',
    ecoFriendly: 'Eco-Friendly',
    routeDetails: 'Route Details',
    duration: 'Duration',
    distance: 'Distance',
    stops: 'Stops',
    routeFare: 'Fare',
    routeType: 'Route Type',
    departureTime: 'Departure Time',
    arrivalTime: 'Arrival Time',
    routeFeatures: 'Route Features',
    smartRoutePlanner: 'Smart Route Planner',
    planYourJourney: 'Plan your journey with AI-powered predictions and eco-friendly route options',
    searchRoutesDestinations: 'Search routes, destinations, or features...',
    smartScheduleFor: 'Smart Schedule for',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    night: 'Night',
    showSmartSchedule: 'Show Smart Schedule',
    hideSmartSchedule: 'Hide Smart Schedule',
    enterStartingPoint: 'Enter starting point...',
    enterDestination: 'Enter destination...',
    // BusMarker component translations
    route: 'Route',
    nextStop: 'Next Stop',
    eta: 'ETA',
    occupancy: 'Occupancy'
  },
  hi: {
    home: 'होम',
    liveTracking: 'लाइव ट्रैकिंग',
    routes: 'मार्ग',
    sustainability: 'स्थिरता',
    profile: 'प्रोफाइल',
    feedback: 'प्रतिक्रिया',
    settings: 'सेटिंग्स',
    login: 'लॉगिन',
    loading: 'लोड हो रहा है',
    pleaseWait: 'कृपया प्रतीक्षा करें...',
    footer: '© {year} ट्रांजिटट्रैक',
    // Home page translations
    smarterCommutes: 'स्मार्ट यात्राएं,',
    greenerCities: 'हरित शहर',
    experienceFuture: 'एआई-संचालित ट्रैकिंग, रीयल-टाइम भीड़ की भविष्यवाणियों और पर्यावरणीय प्रभाव निगरानी के साथ सार्वजनिक परिवहन के भविष्य का अनुभव करें।',
    trackBusesNow: 'अभी बसें ट्रैक करें',
    viewRoutes: 'मार्ग देखें',
    whyChooseTransitTrack: 'ट्रांजिटट्रैक क्यों चुनें?',
    platformCombines: 'हमारा प्लेटफॉर्म आपके यात्रा अनुभव को बदलने के लिए अत्याधुनिक तकनीक को उपयोगकर्ता-अनुकूल डिजाइन के साथ जोड़ता है।',
    "Real-TimeTracking": 'रीयल-टाइम ट्रैकिंग',
    "Real-TimeTrackingDesc": 'सटीक स्थान डेटा और सटीक आगमन भविष्यवाणियों के साथ लाइव बसें ट्रैक करें',
    "AICrowdPrediction": 'एआई भीड़ भविष्यवाणी',
    "AICrowdPredictionDesc": 'स्मार्ट एल्गोरिदम भीड़ घनत्व की भविष्यवाणी करते हैं ताकि आप आरामदायक यात्राओं की योजना बना सकें',
    "CarbonSavingsTracker": 'कार्बन बचत ट्रैकर',
    "CarbonSavingsTrackerDesc": 'अपने पर्यावरणीय प्रभाव की निगरानी करें और देखें कि हर यात्रा के साथ आप कितना CO₂ बचाते हैं',
    findYourBus: 'अपनी बस खोजें',
    enterYourRoute: 'तत्काल ट्रैकिंग प्राप्त करने के लिए अपना मार्ग या गंतव्य दर्ज करें',
    routeNumberPlaceholder: 'रूट नंबर, बस स्टॉप, या गंतव्य...',
    searchNow: 'अभी खोजें',
    searching: 'खोज रहे हैं...',
    popularSearches: 'लोकप्रिय खोजें:',
    liveTransitMap: 'लाइव ट्रांजिट मैप',
    realTimeVisualization: 'आपके क्षेत्र में सक्रिय बसों का रीयल-टाइम विज़ुअलाइज़ेशन',
    activeNow: 'अभी सक्रिय:',
    busesNearby: '{count} बसें आस-पास',
    openFullMap: 'पूरा मानचित्र खोलें',
    advancedFeatures: 'आधुनिक यात्रियों और टिकाऊ परिवहन के लिए डिज़ाइन की गई उन्नत सुविधाएँ',
    readyToTransform: 'अपनी यात्रा को बदलने के लिए तैयार हैं?',
    joinThousands: 'पर्यावरण पर सकारात्मक प्रभाव डालने वाले हजारों स्मार्ट यात्रियों से जुड़ें',
    startTrackingNow: 'अभी ट्रैकिंग शुरू करें',
    seeEnvironmentalImpact: 'पर्यावरणीय प्रभाव देखें',
    dailyCommuters: 'दैनिक यात्री',
    activeRoutes: 'सक्रिय मार्ग',
    accuracyRate: 'सटीकता दर',
    co2TonsSaved: 'CO₂ टन बचाया',
    // LiveTracking.jsx translations
    offlineMode: 'ऑफलाइन मोड - कैश्ड डेटा दिखा रहा है',
    liveBusTracking: 'लाइव बस ट्रैकिंग',
    live: 'लाइव',
    offline: 'ऑफलाइन',
    trackBusesDescription: 'AI-संचालित भीड़ भविष्यवाणियों के साथ वास्तविक समय में बसों को ट्रैक करें',
    searchRoutesStops: 'मार्ग, स्टॉप खोजें...',
    
    // GreenScore.jsx translations
    co2Saved: 'CO₂ बचाया गया',
    tripsTaken: 'यात्राएँ की गईं',
    kmTraveled: 'किमी यात्रा की',
    moneySaved: 'पैसे बचाए',
    treesEquivalent: 'पेड़ लगाए गए',
    comparedToPrivateTransport: 'निजी परिवहन का उपयोग करने की तुलना में',
    equivalentTo: 'के बराबर',
    allCrowds: 'सभी भीड़',
    seatsAvailable: 'सीटें उपलब्ध',
    moderate: 'मध्यम',
    crowded: 'भीड़भाड़',
    // Login page translations
    welcomeBack: 'वापसी पर स्वागत है',
    loginToDashboard: 'अपने डैशबोर्ड तक पहुंचने के लिए लॉगिन करें',
    emailAddress: 'ईमेल पता',
    password: 'पासवर्ड',
    // RoutesTimetable.jsx translations
    planYourRoute: 'अपना मार्ग योजना बनाएं',
    routeFrom: 'से',
    routeTo: 'तक',
    findRoutes: 'मार्ग खोजें',
    ecoFriendly: 'पर्यावरण अनुकूल',
    routeDetails: 'मार्ग विवरण',
    duration: 'अवधि',
    distance: 'दूरी',
    stops: 'स्टॉप',
    routeFare: 'किराया',
    routeType: 'मार्ग प्रकार',
    departureTime: 'प्रस्थान समय',
    arrivalTime: 'आगमन समय',
    routeFeatures: 'मार्ग सुविधाएँ',
    smartRoutePlanner: 'स्मार्ट रूट प्लानर',
    planYourJourney: 'AI-संचालित भविष्यवाणियों और पर्यावरण अनुकूल मार्ग विकल्पों के साथ अपनी यात्रा की योजना बनाएं',
    searchRoutesDestinations: 'मार्ग, गंतव्य, या सुविधाएँ खोजें...',
    smartScheduleFor: 'के लिए स्मार्ट शेड्यूल',
    morning: 'सुबह',
    afternoon: 'दोपहर',
    evening: 'शाम',
    night: 'रात',
    showSmartSchedule: 'स्मार्ट शेड्यूल दिखाएं',
    hideSmartSchedule: 'स्मार्ट शेड्यूल छिपाएं',
    enterStartingPoint: 'प्रारंभिक बिंदु दर्ज करें...',
    enterDestination: 'गंतव्य दर्ज करें...',
    
    // BusMarker component translations
    route: 'मार्ग',
    nextStop: 'अगला स्टॉप',
    eta: 'अनुमानित आगमन समय',
    occupancy: 'भीड़ स्थिति'
  },
  bn: {
    home: 'হোম',
    liveTracking: 'লাইভ ট্র্যাকিং',
    routes: 'রুট',
    sustainability: 'স্থায়িত্ব',
    profile: 'প্রোফাইল',
    feedback: 'প্রতিক্রিয়া',
    settings: 'সেটিংস',
    login: 'লগইন',
    loading: 'লোড হচ্ছে',
    pleaseWait: 'অনুগ্রহ করে অপেক্ষা করুন...',
    footer: '© {year} ট্রানজিটট্র্যাক',
    // Home page translations
    smarterCommutes: 'স্মার্ট যাতায়াত,',
    greenerCities: 'সবুজ শহর',
    experienceFuture: 'AI-চালিত ট্র্যাকিং, রিয়েল-টাইম ভিড় পূর্বাভাস এবং পরিবেশগত প্রভাব পর্যবেক্ষণের সাথে পাবলিক ট্রান্সপোর্টের ভবিষ্যত অনুভব করুন।',
    trackBusesNow: 'এখনই বাস ট্র্যাক করুন',
    viewRoutes: 'রুট দেখুন',
    whyChooseTransitTrack: 'ট্রানজিটট্র্যাক কেন বেছে নেবেন?',
    platformCombines: 'আমাদের প্ল্যাটফর্ম আপনার যাতায়াত অভিজ্ঞতা রূপান্তর করতে অত্যাধুনিক প্রযুক্তি ব্যবহারকারী-বান্ধব ডিজাইনের সাথে সংযুক্ত করে।',
    "Real-TimeTracking": 'রিয়েল-টাইম ট্র্যাকিং',
    "Real-TimeTrackingDesc": 'সঠিক অবস্থান ডেটা এবং সঠিক আগমন পূর্বাভাসের সাথে লাইভ বাস ট্র্যাক করুন',
    "AICrowdPrediction": 'AI ভিড় পূর্বাভাস',
    "AICrowdPredictionDesc": 'স্মার্ট অ্যালগরিদম ভিড়ের ঘনত্ব পূর্বাভাস দেয় যাতে আপনি আরামদায়ক যাত্রা পরিকল্পনা করতে পারেন',
    "CarbonSavingsTracker": 'কার্বন সেভিংস ট্র্যাকার',
    "CarbonSavingsTrackerDesc": 'আপনার পরিবেশগত প্রভাব পর্যবেক্ষণ করুন এবং দেখুন প্রতিটি যাত্রায় আপনি কত CO₂ সাশ্রয় করেন',
    findYourBus: 'আপনার বাস খুঁজুন',
    enterYourRoute: 'তাৎক্ষণিক ট্র্যাকিংয়ের জন্য আপনার রুট বা গন্তব্য লিখুন',
    routeNumberPlaceholder: 'রুট নম্বর, বাস স্টপ, বা গন্তব্য...',
    searchNow: 'এখনই খুঁজুন',
    searching: 'খোঁজা হচ্ছে...',
    popularSearches: 'জনপ্রিয় অনুসন্ধান:',
    liveTransitMap: 'লাইভ ট্রানজিট ম্যাপ',
    realTimeVisualization: 'আপনার এলাকায় সক্রিয় বাসের রিয়েল-টাইম ভিজ্যুয়ালাইজেশন',
    activeNow: 'এখন সক্রিয়:',
    busesNearby: '{count} বাস কাছাকাছি',
    openFullMap: 'সম্পূর্ণ ম্যাপ খুলুন',
    advancedFeatures: 'আধুনিক যাত্রী এবং টেকসই পরিবহনের জন্য ডিজাইন করা উন্নত বৈশিষ্ট্য',
    readyToTransform: 'আপনার যাতায়াত পরিবর্তন করতে প্রস্তুত?',
    joinThousands: 'পরিবেশে ইতিবাচক প্রভাব ফেলে এমন হাজার হাজার স্মার্ট যাত্রীদের সাথে যোগ দিন',
    startTrackingNow: 'এখনই ট্র্যাকিং শুরু করুন',
    seeEnvironmentalImpact: 'পরিবেশগত প্রভাব দেখুন',
    dailyCommuters: 'দৈনিক যাত্রী',
    activeRoutes: 'সক্রিয় রুট',
    accuracyRate: 'সঠিকতার হার',
    co2TonsSaved: 'CO₂ টন সাশ্রয় করা হয়েছে',
    // LiveTracking.jsx translations
    offlineMode: 'অফলাইন মোড - ক্যাশে করা ডেটা দেখাচ্ছে',
    liveBusTracking: 'লাইভ বাস ট্র্যাকিং',
    live: 'লাইভ',
    offline: 'অফলাইন',
    trackBusesDescription: 'AI-চালিত ভিড় পূর্বাভাসের সাথে রিয়েল-টাইমে বাস ট্র্যাক করুন',
    searchRoutesStops: 'রুট, স্টপ অনুসন্ধান করুন...',
    
    // GreenScore.jsx translations
    co2Saved: 'CO₂ সংরক্ষণ করা হয়েছে',
    tripsTaken: 'যাত্রা করা হয়েছে',
    kmTraveled: 'কিমি ভ্রমণ করেছে',
    moneySaved: 'অর্থ সঞ্চয় করা হয়েছে',
    treesEquivalent: 'গাছ রোপণের সমতুল্য',
    comparedToPrivateTransport: 'ব্যক্তিগত পরিবহন ব্যবহারের তুলনায়',
    equivalentTo: 'সমতুল্য',
    allCrowds: 'সব ধরনের ভিড়',
    seatsAvailable: 'আসন উপলব্ধ',
    moderate: 'মাঝারি',
    crowded: 'ভিড়',
    // Login page translations
    welcomeBack: 'ফিরে আসায় স্বাগতম',
    loginToDashboard: 'আপনার ড্যাশবোর্ড অ্যাক্সেস করতে লগইন করুন',
    emailAddress: 'ইমেল ঠিকানা',
    password: 'পাসওয়ার্ড',
    // RoutesTimetable.jsx translations
    planYourRoute: 'আপনার রুট পরিকল্পনা করুন',
    from: 'থেকে',
    to: 'পর্যন্ত',
    findRoutes: 'রুট খুঁজুন',
    ecoFriendly: 'পরিবেশ বান্ধব',
    routeDetails: 'রুট বিবরণ',
    duration: 'সময়কাল',
    distance: 'দূরত্ব',
    stops: 'স্টপ',
    fare: 'ভাড়া',
    routeType: 'রুট প্রকার',
    departureTime: 'প্রস্থান সময়',
    arrivalTime: 'আগমন সময়',
    routeFeatures: 'রুট বৈশিষ্ট্য',
    smartRoutePlanner: 'স্মার্ট রুট প্ল্যানার',
    planYourJourney: 'AI-চালিত পূর্বাভাস এবং পরিবেশ বান্ধব রুট বিকল্পগুলি সহ আপনার যাত্রা পরিকল্পনা করুন',
    searchRoutesDestinations: 'রুট, গন্তব্য, বা বৈশিষ্ট্য অনুসন্ধান করুন...',
    smartScheduleFor: 'জন্য স্মার্ট সময়সূচী',
    morning: 'সকাল',
    afternoon: 'দুপুর',
    evening: 'সন্ধ্যা',
    night: 'রাত',
    showSmartSchedule: 'স্মার্ট সময়সূচী দেখান',
    hideSmartSchedule: 'স্মার্ট সময়সূচী লুকান',
    enterStartingPoint: 'শুরুর বিন্দু লিখুন...',
    enterDestination: 'গন্তব্য লিখুন...',
    
    // BusMarker component translations
    route: 'রুট',
    nextStop: 'পরবর্তী স্টপ',
    eta: 'আনুমানিক আগমন সময়',
    occupancy: 'ভিড়ের অবস্থা'
  },
  ta: {
    home: 'முகப்பு',
    liveTracking: 'நேரலை கண்காணிப்பு',
    routes: 'வழிகள்',
    sustainability: 'நிலைத்தன்மை',
    profile: 'சுயவிவரம்',
    feedback: 'கருத்து',
    settings: 'அமைப்புகள்',
    login: 'உள்நுழைய',
    loading: 'ஏற்றுகிறது',
    pleaseWait: 'தயவுசெய்து காத்திருக்கவும்...',
    footer: '© {year} டிரான்சிட்டிராக்',
    // Home page translations
    smarterCommutes: 'புத்திசாலித்தனமான பயணங்கள்,',
    greenerCities: 'பசுமையான நகரங்கள்',
    experienceFuture: 'AI-சக்தி கண்காணிப்பு, நிகழ்நேர கூட்ட கணிப்புகள் மற்றும் சுற்றுச்சூழல் தாக்க கண்காணிப்புடன் பொது போக்குவரத்தின் எதிர்காலத்தை அனுபவிக்கவும்.',
    trackBusesNow: 'இப்போது பேருந்துகளைக் கண்காணிக்கவும்',
    viewRoutes: 'வழிகளைக் காண்க',
    whyChooseTransitTrack: 'டிரான்சிட்டிராக்கை ஏன் தேர்வு செய்ய வேண்டும்?',
    platformCombines: 'எங்கள் தளம் உங்கள் பயண அனுபவத்தை மாற்றுவதற்கு நவீன தொழில்நுட்பத்தை பயனர் நட்பு வடிவமைப்புடன் இணைக்கிறது.',
    "Real-TimeTracking": 'நிகழ்நேர கண்காணிப்பு',
    "Real-TimeTrackingDesc": 'துல்லியமான இருப்பிட தரவு மற்றும் துல்லியமான வருகை கணிப்புகளுடன் நேரலை பேருந்துகளைக் கண்காணிக்கவும்',
    "AICrowdPrediction": 'AI கூட்ட கணிப்பு',
    "AICrowdPredictionDesc": 'வசதியான பயணங்களைத் திட்டமிட உதவும் வகையில் கூட்ட அடர்த்தியை ஸ்மார்ட் அல்காரிதம்கள் கணிக்கின்றன',
    "CarbonSavingsTracker": 'கார்பன் சேமிப்பு கண்காணிப்பு',
    "CarbonSavingsTrackerDesc": 'உங்கள் சுற்றுச்சூழல் தாக்கத்தைக் கண்காணிக்கவும், ஒவ்வொரு பயணத்திலும் நீங்கள் எவ்வளவு CO₂ சேமிக்கிறீர்கள் என்பதைப் பார்க்கவும்',
    findYourBus: 'உங்கள் பேருந்தைக் கண்டறியவும்',
    enterYourRoute: 'உடனடி கண்காணிப்பைப் பெற உங்கள் வழி அல்லது இலக்கை உள்ளிடவும்',
    routeNumberPlaceholder: 'வழித்தட எண், பேருந்து நிறுத்தம், அல்லது இலக்கு...',
    searchNow: 'இப்போது தேடுங்கள்',
    searching: 'தேடுகிறது...',
    popularSearches: 'பிரபலமான தேடல்கள்:',
    liveTransitMap: 'நேரலை போக்குவரத்து வரைபடம்',
    realTimeVisualization: 'உங்கள் பகுதியில் செயலில் உள்ள பேருந்துகளின் நிகழ்நேர காட்சிப்படுத்தல்',
    activeNow: 'இப்போது செயலில்:',
    busesNearby: '{count} பேருந்துகள் அருகில்',
    openFullMap: 'முழு வரைபடத்தைத் திறக்கவும்',
    advancedFeatures: 'நவீன பயணிகள் மற்றும் நிலையான போக்குவரத்துக்காக வடிவமைக்கப்பட்ட மேம்பட்ட அம்சங்கள்',
    readyToTransform: 'உங்கள் பயணத்தை மாற்ற தயாரா?',
    joinThousands: 'சுற்றுச்சூழலில் நேர்மறையான தாக்கத்தை ஏற்படுத்தும் ஆயிரக்கணக்கான புத்திசாலி பயணிகளுடன் இணையுங்கள்',
    startTrackingNow: 'இப்போது கண்காணிக்கத் தொடங்குங்கள்',
    seeEnvironmentalImpact: 'சுற்றுச்சூழல் தாக்கத்தைப் பார்க்கவும்',
    dailyCommuters: 'தினசரி பயணிகள்',
    activeRoutes: 'செயலில் உள்ள வழிகள்',
    accuracyRate: 'துல்லியத்தன்மை விகிதம்',
    co2TonsSaved: 'CO₂ டன்கள் சேமிக்கப்பட்டன',
    // LiveTracking.jsx translations
    offlineMode: 'ஆஃப்லைன் பயன்முறை - தற்காலிகமாக சேமிக்கப்பட்ட தரவைக் காட்டுகிறது',
    liveBusTracking: 'நேரலை பேருந்து கண்காணிப்பு',
    live: 'நேரலை',
    offline: 'ஆஃப்லைன்',
    trackBusesDescription: 'AI-சக்தி வாய்ந்த கூட்ட கணிப்புகளுடன் நிகழ்நேரத்தில் பேருந்துகளைக் கண்காணிக்கவும்',
    searchRoutesStops: 'வழித்தடங்கள், நிறுத்தங்களைத் தேடுங்கள்...',
    
    // GreenScore.jsx translations
    co2Saved: 'CO₂ சேமிக்கப்பட்டது',
    tripsTaken: 'பயணங்கள் மேற்கொள்ளப்பட்டன',
    kmTraveled: 'கிமீ பயணித்தது',
    moneySaved: 'பணம் சேமிக்கப்பட்டது',
    treesEquivalent: 'மரங்கள் நடப்பட்டதற்கு சமமானது',
    comparedToPrivateTransport: 'தனியார் போக்குவரத்தைப் பயன்படுத்துவதுடன் ஒப்பிடுகையில்',
    equivalentTo: 'இதற்கு சமமானது',
    allCrowds: 'அனைத்து கூட்டங்கள்',
    seatsAvailable: 'இருக்கைகள் உள்ளன',
    moderate: 'மிதமான',
    crowded: 'கூட்டமான',
    // Login.jsx translations
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    loginToDashboard: 'உங்கள் டாஷ்போர்டை அணுக உள்நுழையவும்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    password: 'கடவுச்சொல்',
    // RoutesTimetable.jsx translations
    planYourRoute: 'உங்கள் வழித்தடத்தை திட்டமிடுங்கள்',
    from: 'இருந்து',
    to: 'வரை',
    findRoutes: 'வழிகளைக் கண்டறியவும்',
    ecoFriendly: 'சுற்றுச்சூழல் நட்பு',
    routeDetails: 'வழித்தட விவரங்கள்',
    duration: 'கால அளவு',
    distance: 'தூரம்',
    stops: 'நிறுத்தங்கள்',
    fare: 'கட்டணம்',
    routeType: 'வழித்தட வகை',
    departureTime: 'புறப்படும் நேரம்',
    arrivalTime: 'வந்தடையும் நேரம்',
    routeFeatures: 'வழித்தட அம்சங்கள்',
    smartRoutePlanner: 'ஸ்மார்ட் வழித்தட திட்டமிடல்',
    planYourJourney: 'AI-ஆல் இயக்கப்படும் கணிப்புகள் மற்றும் சுற்றுச்சூழல் நட்பு வழித்தட விருப்பங்களுடன் உங்கள் பயணத்தை திட்டமிடுங்கள்',
    searchRoutesDestinations: 'வழிகள், இலக்குகள் அல்லது அம்சங்களைத் தேடுங்கள்...',
    smartScheduleFor: 'க்கான ஸ்மார்ட் அட்டவணை',
    morning: 'காலை',
    afternoon: 'மதியம்',
    evening: 'மாலை',
    night: 'இரவு',
    showSmartSchedule: 'ஸ்மார்ட் அட்டவணையைக் காட்டு',
    hideSmartSchedule: 'ஸ்மார்ட் அட்டவணையை மறை',
    enterStartingPoint: 'தொடக்க புள்ளியை உள்ளிடவும்...',
    enterDestination: 'இலக்கை உள்ளிடவும்...',
    
    // BusMarker component translations
    route: 'வழித்தடம்',
    nextStop: 'அடுத்த நிறுத்தம்',
    eta: 'வருகை நேரம்',
    occupancy: 'கூட்ட நிலை'
  },
  te: {
    home: 'హోమ్',
    liveTracking: 'లైవ్ ట్రాకింగ్',
    routes: 'మార్గాలు',
    sustainability: 'స్థిరత్వం',
    profile: 'ప్రొఫైల్',
    feedback: 'అభిప్రాయం',
    settings: 'సెట్టింగులు',
    login: 'లాగిన్',
    loading: 'లోడ్ అవుతోంది',
    pleaseWait: 'దయచేసి వేచి ఉండండి...',
    footer: '© {year} ట్రాన్సిట్ ట్రాక్',
    // Home page translations
    smarterCommutes: 'స్మార్టర్ కమ్యూట్స్,',
    greenerCities: 'గ్రీనర్ సిటీస్',
    experienceFuture: 'AI-ఆధారిత ట్రాకింగ్, రియల్-టైమ్ రద్దీ అంచనాలు మరియు పర్యావరణ ప్రభావ పర్యవేక్షణతో పబ్లిక్ ట్రాన్స్‌పోర్టేషన్ భవిష్యత్తును అనుభవించండి.',
    trackBusesNow: 'ఇప్పుడే బస్సులను ట్రాక్ చేయండి',
    viewRoutes: 'మార్గాలను చూడండి',
    whyChooseTransitTrack: 'ట్రాన్సిట్ ట్రాక్‌ని ఎందుకు ఎంచుకోవాలి?',
    platformCombines: 'మా ప్లాట్‌ఫారమ్ మీ కమ్యూటింగ్ అనుభవాన్ని మార్చడానికి అత్యాధునిక సాంకేతికతను యూజర్-ఫ్రెండ్లీ డిజైన్‌తో జతచేస్తుంది.',
    "Real-TimeTracking": 'రియల్-టైమ్ ట్రాకింగ్',
    "Real-TimeTrackingDesc": 'ఖచ్చితమైన స్థాన డేటా మరియు ఖచ్చితమైన రాక అంచనాలతో లైవ్ బస్సులను ట్రాక్ చేయండి',
    "AICrowdPrediction": 'AI రద్దీ అంచనా',
    "AICrowdPredictionDesc": 'స్మార్ట్ అల్గారిథమ్‌లు రద్దీ సాంద్రతను అంచనా వేస్తాయి, తద్వారా మీరు సౌకర్యవంతమైన ప్రయాణాలను ప్లాన్ చేసుకోవచ్చు',
    "CarbonSavingsTracker": 'కార్బన్ సేవింగ్స్ ట్రాకర్',
    "CarbonSavingsTrackerDesc": 'మీ పర్యావరణ ప్రభావాన్ని పర్యవేక్షించండి మరియు ప్రతి ట్రిప్‌తో మీరు ఎంత CO₂ని ఆదా చేస్తున్నారో చూడండి',
    findYourBus: 'మీ బస్సును కనుగొనండి',
    enterYourRoute: 'తక్షణ ట్రాకింగ్ పొందడానికి మీ మార్గం లేదా గమ్యస్థానాన్ని నమోదు చేయండి',
    routeNumberPlaceholder: 'మార్గం సంఖ్య, బస్సు స్టాప్, లేదా గమ్యస్థానం...',
    searchNow: 'ఇప్పుడే శోధించండి',
    searching: 'శోధిస్తోంది...',
    popularSearches: 'ప్రజాదరణ పొందిన శోధనలు:',
    liveTransitMap: 'లైవ్ ట్రాన్సిట్ మ్యాప్',
    realTimeVisualization: 'మీ ప్రాంతంలో యాక్టివ్ బస్సుల రియల్-టైమ్ విజువలైజేషన్',
    activeNow: 'ప్రస్తుతం యాక్టివ్:',
    busesNearby: '{count} బస్సులు సమీపంలో ఉన్నాయి',
    openFullMap: 'పూర్తి మ్యాప్‌ని తెరవండి',
    advancedFeatures: 'ఆధునిక కమ్యూటర్లు మరియు సుస్థిర రవాణా కోసం రూపొందించబడిన అధునాతన ఫీచర్లు',
    readyToTransform: 'మీ కమ్యూట్‌ని మార్చడానికి సిద్ధంగా ఉన్నారా?',
    joinThousands: 'పర్యావరణంపై సానుకూల ప్రభావాన్ని చూపే వేలాది మంది స్మార్ట్ కమ్యూటర్లతో చేరండి',
    startTrackingNow: 'ఇప్పుడే ట్రాకింగ్ ప్రారంభించండి',
    seeEnvironmentalImpact: 'పర్యావరణ ప్రభావాన్ని చూడండి',
    dailyCommuters: 'రోజువారీ కమ్యూటర్లు',
    activeRoutes: 'యాక్టివ్ మార్గాలు',
    accuracyRate: 'ఖచ్చితత్వ రేటు',
    co2TonsSaved: 'CO₂ టన్నులు ఆదా చేయబడ్డాయి',
    // LiveTracking.jsx translations
    offlineMode: 'ఆఫ్‌లైన్ మోడ్ - కాష్ చేయబడిన డేటాను చూపుతోంది',
    liveBusTracking: 'లైవ్ బస్ ట్రాకింగ్',
    live: 'లైవ్',
    offline: 'ఆఫ్‌లైన్',
    trackBusesDescription: 'AI-పవర్డ్ రద్దీ అంచనాలతో రియల్-టైమ్‌లో బస్సులను ట్రాక్ చేయండి',
    searchRoutesStops: 'మార్గాలు, స్టాప్‌లు శోధించండి...',
    
    // GreenScore.jsx translations
    co2Saved: 'CO₂ ఆదా చేయబడింది',
    tripsTaken: 'ప్రయాణాలు చేసారు',
    kmTraveled: 'కి.మీ ప్రయాణించారు',
    moneySaved: 'డబ్బు ఆదా చేయబడింది',
    treesEquivalent: 'నాటిన చెట్లకు సమానం',
    comparedToPrivateTransport: 'ప్రైవేట్ రవాణాతో పోలిస్తే',
    allCrowds: 'అన్ని రద్దీలు',
    seatsAvailable: 'సీట్లు అందుబాటులో ఉన్నాయి',
    moderate: 'మోస్తరు',
    crowded: 'రద్దీగా ఉంది',
    // Login.jsx translations
    welcomeBack: 'తిరిగి స్వాగతం',
    loginToDashboard: 'మీ డాష్‌బోర్డ్‌ను యాక్సెస్ చేయడానికి లాగిన్ చేయండి',
    emailAddress: 'ఇమెయిల్ చిరునామా',
    password: 'పాస్‌వర్డ్',
    // RoutesTimetable.jsx translations
    planYourRoute: 'మీ మార్గాన్ని ప్లాన్ చేయండి',
    from: 'నుండి',
    to: 'వరకు',
    findRoutes: 'మార్గాలను కనుగొనండి',
    ecoFriendly: 'పర్యావరణ అనుకూల',
    routeDetails: 'మార్గం వివరాలు',
    duration: 'వ్యవధి',
    distance: 'దూరం',
    stops: 'స్టాప్‌లు',
    fare: 'ఛార్జీ',
    routeType: 'మార్గం రకం',
    departureTime: 'బయలుదేరే సమయం',
    arrivalTime: 'చేరుకునే సమయం',
    routeFeatures: 'మార్గం ఫీచర్లు',
    smartRoutePlanner: 'స్మార్ట్ మార్గ ప్లానర్',
    planYourJourney: 'AI-ఆధారిత అంచనాలు మరియు పర్యావరణ అనుకూల మార్గ ఎంపికలతో మీ ప్రయాణాన్ని ప్లాన్ చేయండి',
    searchRoutesDestinations: 'మార్గాలు, గమ్యస్థానాలు లేదా ఫీచర్లను శోధించండి...',
    smartScheduleFor: 'కోసం స్మార్ట్ షెడ్యూల్',
    morning: 'ఉదయం',
    afternoon: 'మధ్యాహ్నం',
    evening: 'సాయంత్రం',
    night: 'రాత్రి',
    showSmartSchedule: 'స్మార్ట్ షెడ్యూల్ చూపించు',
    hideSmartSchedule: 'స్మార్ట్ షెడ్యూల్ దాచు',
    enterStartingPoint: 'ప్రారంభ స్థానాన్ని నమోదు చేయండి...',
    enterDestination: 'గమ్యస్థానాన్ని నమోదు చేయండి...',
    
    // BusMarker component translations
    route: 'మార్గం',
    nextStop: 'తదుపరి స్టాప్',
    eta: 'చేరుకునే సమయం',
    occupancy: 'ఆక్రమణ స్థితి'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('lang') || 'en');

  useEffect(() => {
    // Save language preference to localStorage
    localStorage.setItem('lang', language);
    // Update html lang attribute
    document.documentElement.setAttribute('lang', language);
  }, [language]);

  const translate = (key, params = {}) => {
    const translation = translations[language]?.[key] || translations.en[key] || key;
    
    // Replace parameters in translation strings
    return translation.replace(/{([^}]+)}/g, (_, param) => {
      return params[param] !== undefined ? params[param] : `{${param}}`;
    });
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translate, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};